Repository govau/design-system-components, pull requests merged in 2018-07, with the labels that each got.

#438 Update scaffolding template from uikit -> au and dependencies
  .templates/new-module/LICENSE
  .templates/new-module/package.json
  .templates/new-module/src/js/jquery.js
  .templates/new-module/src/js/module.js
  .templates/new-module/src/js/react.js
  .templates/new-module/tests/react/index.js
Labels: enhancement

#436 Add outline offset to default style, for easier overrides
  packages/core/CHANGELOG.md
  packages/core/README.md
  packages/core/package.json
  packages/core/src/sass/_globals.scss
Labels: enhancement

#434 Open and close accordion when specific state changes
  packages/accordion/CHANGELOG.md
  packages/accordion/README.md
  packages/accordion/package.json
  packages/accordion/src/js/react.js
  packages/accordion/tests/react/index.js
  uikit.json
Labels: enhancement

#435 link-list children in correct location
  packages/breadcrumbs/CHANGELOG.md
  packages/breadcrumbs/README.md
  packages/breadcrumbs/package-lock.json
  packages/breadcrumbs/package.json
  packages/inpage-nav/CHANGELOG.md
  packages/inpage-nav/README.md
  packages/inpage-nav/package-lock.json
  packages/inpage-nav/package.json
  packages/keyword-list/CHANGELOG.md
  packages/keyword-list/README.md
  packages/keyword-list/package-lock.json
  packages/keyword-list/package.json
  packages/link-list/CHANGELOG.md
  packages/link-list/README.md
  packages/link-list/package.json
  packages/link-list/src/js/react.js
Labels: enhancement

#431 Side navigation
  .templates/test-assets/_style.scss
  README.md
  packages/side-nav/CHANGELOG.md
  packages/side-nav/LICENSE
  packages/side-nav/README.md
  packages/side-nav/package-lock.json
  packages/side-nav/package.json
  packages/side-nav/src/js/jquery.js
  packages/side-nav/src/js/module.js
  packages/side-nav/src/js/react.js
  packages/side-nav/src/sass/_dependencies.scss
  packages/side-nav/src/sass/_globals.scss
  packages/side-nav/src/sass/_module.scss
  packages/side-nav/src/sass/_print.scss
  packages/side-nav/tests/index.html
  packages/side-nav/tests/jquery/index.html
  packages/side-nav/tests/jquery/test.scss
  packages/side-nav/tests/react/.babelrc
  packages/side-nav/tests/react/index.html
  packages/side-nav/tests/react/index.js
  packages/side-nav/tests/react/webpack.config.js
  packages/side-nav/tests/site/index.html
  packages/side-nav/tests/site/test.scss
  uikit.json
Labels: new module

#444 Add sketch to FAQ
  FAQ.md
Labels: documentation

#443 HeaderBrand without link now defaults to div
  packages/header/CHANGELOG.md
  packages/header/README.md
  packages/header/package.json
  packages/header/src/js/react.js
  packages/header/tests/react/index.js
Labels: bug

#445 FAQ docs, header patch
  FAQ.md
  packages/header/CHANGELOG.md
  packages/header/README.md
  packages/header/package.json
  packages/header/src/js/react.js
  packages/header/tests/react/index.js
Labels: bug, enhancement

#447 Remove aria-hidden as css display toggles screen reader ability
  packages/accordion/CHANGELOG.md
  packages/accordion/README.md
  packages/accordion/package.json
  packages/accordion/src/js/jquery.js
  packages/accordion/src/js/module.js
  packages/accordion/src/js/react.js
  packages/accordion/tests/site/index.html
  packages/side-nav/CHANGELOG.md
  packages/side-nav/README.md
  packages/side-nav/package.json
  packages/side-nav/tests/jquery/index.html
  packages/side-nav/tests/site/index.html
  uikit.json
Labels: accessibility, bug

#449 Update uikit.json
  uikit.json
Labels: enhancement

#451 Update pancake-sass for side-nav
  packages/side-nav/CHANGELOG.md
  packages/side-nav/README.md
  packages/side-nav/package-lock.json
  packages/side-nav/package.json
Labels: enhancement

#456 Update side navigation to use correct semantic html ( nav -> aside )
  packages/side-nav/CHANGELOG.md
  packages/side-nav/README.md
  packages/side-nav/package.json
  packages/side-nav/src/js/react.js
  packages/side-nav/tests/site/index.html
  uikit.json
Labels: accessibility, enhancement
