Repository govau/design-system-components, pull requests merged in 2018-11, with the labels that each got.

#545 Revert main nav active item to link
  packages/main-nav/CHANGELOG.md
  packages/main-nav/README.md
  packages/main-nav/package.json
  packages/main-nav/src/js/react.js
  packages/main-nav/src/sass/_module.scss
  packages/main-nav/tests/jquery/index.html
  packages/main-nav/tests/site/index.html
  uikit.json
Labels: bug, enhancement

#551 Fix docs for control inputs with initial checked state
  packages/control-input/CHANGELOG.md
  packages/control-input/README.md
  packages/control-input/package.json
  packages/control-input/tests/react/index.js
Labels: bug

#557 change control input react prop from 'checked' to 'defaultChecked'
  packages/control-input/CHANGELOG.md
  packages/control-input/README.md
  packages/control-input/package.json
  packages/control-input/tests/react/index.js
Labels: enhancement

#559 Update animate and project dependencies
  package-lock.json
  packages/animate/CHANGELOG.md
  packages/animate/README.md
  packages/animate/package-lock.json
  packages/animate/package.json
  uikit.json
Labels: enhancement

#546 Fix issue with accordion state, add state test to side navigation
  packages/accordion/CHANGELOG.md
  packages/accordion/README.md
  packages/accordion/package.json
  packages/accordion/src/js/module.js
  packages/accordion/src/js/react.js
  packages/accordion/tests/react/index.js
  packages/side-nav/CHANGELOG.md
  packages/side-nav/README.md
  packages/side-nav/package.json
  packages/side-nav/tests/react/index.js
  uikit.json
Labels: bug

#561 Fix issue with accordion state, add state test to side navigation
  packages/accordion/CHANGELOG.md
  packages/accordion/README.md
  packages/accordion/package.json
  packages/accordion/src/js/module.js
  packages/accordion/src/js/react.js
  packages/accordion/tests/react/index.js
  packages/side-nav/CHANGELOG.md
  packages/side-nav/README.md
  packages/side-nav/package.json
  packages/side-nav/tests/react/index.js
  uikit.json
Labels: bug, enhancement

#563 Updated side nav example menu, fix broken link on react state example
  packages/animate/CHANGELOG.md
  packages/animate/README.md
  packages/animate/package-lock.json
  packages/animate/package.json
  packages/side-nav/CHANGELOG.md
  packages/side-nav/README.md
  packages/side-nav/tests/react/index.js
  uikit.json
Labels: enhancement

#566 -test deployments create test environment
  .circleci/config.yml
Labels: bug
