Repository govau/design-system-components, pull requests merged in 2018-09, with the labels that each got.

#495 Update the html5 markup with aria-label attribute
  packages/footer/CHANGELOG.md
  packages/footer/README.md
  packages/footer/package.json
  packages/footer/src/js/react.js
  packages/footer/tests/site/index.html
  packages/inpage-nav/CHANGELOG.md
  packages/inpage-nav/README.md
  packages/inpage-nav/package.json
  packages/inpage-nav/src/js/react.js
  packages/inpage-nav/tests/site/index.html
  packages/main-nav/CHANGELOG.md
  packages/main-nav/README.md
  packages/main-nav/package.json
  packages/main-nav/src/js/react.js
  packages/main-nav/tests/jquery/index.html
  packages/main-nav/tests/site/index.html
  packages/side-nav/CHANGELOG.md
  packages/side-nav/README.md
  packages/side-nav/package.json
  packages/side-nav/src/js/react.js
  packages/side-nav/tests/jquery/index.html
  packages/side-nav/tests/site/index.html
  packages/skip-link/CHANGELOG.md
  packages/skip-link/README.md
  packages/skip-link/package.json
  packages/skip-link/src/js/react.js
  packages/skip-link/tests/site/index.html
  uikit.json
Labels: accessibility, enhancement

#441 Zero downtime deployment update
  .circleci/config.yml
  deploy/manifest-production.yml
  deploy/manifest-staging.yml
  deploy/manifest-testing.yml
Labels: enhancement

#496 Fix/accordion react closed state changes
  packages/accordion/CHANGELOG.md
  packages/accordion/README.md
  packages/accordion/package.json
  packages/accordion/src/js/react.js
  packages/accordion/tests/react/index.js
Labels: enhancement

#500 HTML5 aria-labels, zero down time deployment update
  .circleci/config.yml
  .deploy/manifest-production.yml
  .deploy/manifest-staging.yml
  .deploy/manifest-testing.yml
  packages/footer/CHANGELOG.md
  packages/footer/README.md
  packages/footer/package.json
  packages/footer/src/js/react.js
  packages/footer/tests/site/index.html
  packages/inpage-nav/CHANGELOG.md
  packages/inpage-nav/README.md
  packages/inpage-nav/package.json
  packages/inpage-nav/src/js/react.js
  packages/inpage-nav/tests/site/index.html
  packages/main-nav/CHANGELOG.md
  packages/main-nav/README.md
  packages/main-nav/package.json
  packages/main-nav/src/js/react.js
  packages/main-nav/tests/jquery/index.html
  packages/main-nav/tests/site/index.html
  packages/side-nav/CHANGELOG.md
  packages/side-nav/README.md
  packages/side-nav/package.json
  packages/side-nav/src/js/react.js
  packages/side-nav/tests/jquery/index.html
  packages/side-nav/tests/site/index.html
  packages/skip-link/CHANGELOG.md
  packages/skip-link/README.md
  packages/skip-link/package.json
  packages/skip-link/src/js/react.js
  packages/skip-link/tests/site/index.html
  uikit.json
Labels: accessibility, enhancement

#511 Update the browser-sync dependency for the animate package
  packages/animate/CHANGELOG.md
  packages/animate/README.md
  packages/animate/package-lock.json
  packages/animate/package.json
  uikit.json
Labels: enhancement

#513 Update pa11y
  .circleci/config.yml
  README.md
  package-lock.json
  package.json
  packages/core/tests/site/index.html
  scripts/a11y.js
Labels: enhancement

#518 Removed footer role contentinfo
  packages/footer/CHANGELOG.md
  packages/footer/README.md
  packages/footer/package.json
  packages/footer/src/js/react.js
  packages/footer/tests/site/index.html
Labels: enhancement

#519 Remove `role="contentinfo"` for footer
  packages/footer/CHANGELOG.md
  packages/footer/README.md
  packages/footer/package.json
  packages/footer/src/js/react.js
  packages/footer/tests/site/index.html
Labels: enhancement

#520 Fixed main nav not taking in props
  packages/main-nav/CHANGELOG.md
  packages/main-nav/README.md
  packages/main-nav/package.json
  packages/main-nav/src/js/react.js
  uikit.json
Labels: bug

#522 Fix issue of main nav not accepting props
  packages/main-nav/CHANGELOG.md
  packages/main-nav/README.md
  packages/main-nav/package.json
  packages/main-nav/src/js/react.js
  uikit.json
Labels: bug

#523 Added back role=contentinfo in footer
  packages/footer/CHANGELOG.md
  packages/footer/README.md
  packages/footer/package.json
  packages/footer/src/js/react.js
  packages/footer/tests/site/index.html
Labels: accessibility

#524 Added back `role="contentinfo"` to footer
  packages/footer/CHANGELOG.md
  packages/footer/README.md
  packages/footer/package.json
  packages/footer/src/js/react.js
  packages/footer/tests/site/index.html
Labels: accessibility
