Repository govau/design-system-components, pull requests merged in 2018-08, with the labels that each got.

#461 Removed border from header brand image ie8, ie9 and ie10
  packages/header/CHANGELOG.md
  packages/header/README.md
  packages/header/package.json
  packages/header/src/sass/_module.scss
  uikit.json
Labels: bug

#463 Removed incorrect side-nav margin on desktop devices
  packages/side-nav/CHANGELOG.md
  packages/side-nav/README.md
  packages/side-nav/package.json
  packages/side-nav/src/sass/_module.scss
  uikit.json
Labels: bug

#464 Made URL for external links visible in print preview
  packages/body/CHANGELOG.md
  packages/body/README.md
  packages/body/package.json
  packages/body/src/sass/_print.scss
  uikit.json
Labels: bug

#465 Remove 🌲 as it takes 11 seconds ⚰️
  .circleci/config.yml
Labels: enhancement

#468 Side navigation active state in react
  packages/side-nav/CHANGELOG.md
  packages/side-nav/README.md
  packages/side-nav/package.json
  packages/side-nav/src/js/react.js
  packages/side-nav/tests/react/index.js
Labels: enhancement

#476 Fixing bug where openSize of 0 gets turned into auto
  packages/animate/CHANGELOG.md
  packages/animate/README.md
  packages/animate/package.json
  packages/animate/src/js/module.js
  uikit.json
Labels: bug

#437 Main navigation
  README.md
  packages/accordion/README.md
  packages/accordion/src/js/jquery.js
  packages/accordion/src/js/react.js
  packages/main-nav/CHANGELOG.md
  packages/main-nav/LICENSE
  packages/main-nav/README.md
  packages/main-nav/package-lock.json
  packages/main-nav/package.json
  packages/main-nav/src/js/jquery.js
  packages/main-nav/src/js/module.js
  packages/main-nav/src/js/react.js
  packages/main-nav/src/sass/_dependencies.scss
  packages/main-nav/src/sass/_globals.scss
  packages/main-nav/src/sass/_module.scss
  packages/main-nav/src/sass/_print.scss
  packages/main-nav/tests/index.html
  packages/main-nav/tests/jquery/index.html
  packages/main-nav/tests/jquery/test.scss
  packages/main-nav/tests/react/.babelrc
  packages/main-nav/tests/react/index.html
  packages/main-nav/tests/react/index.js
  packages/main-nav/tests/react/webpack.config.js
  packages/main-nav/tests/site/index.html
  packages/main-nav/tests/site/test.scss
  packages/side-nav/tests/site/index.html
  uikit.json
Labels: module: main-nav, new module

#478 Update issue templates
  .github/ISSUE_TEMPLATE/----bug-report.md
  .github/ISSUE_TEMPLATE/---feature-request.md
  .github/ISSUE_TEMPLATE/---support-question.md
  .github/ISSUE_TEMPLATE/--join-the-community.md
  .github/ISSUE_TEMPLATE/-design-system-website.md
Labels: enhancement

#484 Feature/fix main nav docs
  packages/main-nav/README.md
Labels: documentation

#488 Fix prop types bug
  packages/main-nav/src/js/react.js
Labels: bug
