Repository govau/design-system-components, pull requests merged in 2019-04, with the labels that each got.

#708 Update contributing docs
  CONTRIBUTING.md
Labels: documentation

#709 Updating contributing docs
  CONTRIBUTING.md
Labels: documentation

#712 Content updates
  FAQ.md
Labels: documentation

#715 Remove word 'navigation' from aria-label in footer
  packages/footer/CHANGELOG.md
  packages/footer/README.md
  packages/footer/package.json
  packages/footer/src/js/react.js
  packages/footer/tests/site/index.html
Labels: accessibility

#714 Remove 'navigation' from aria-label in main nav
  packages/main-nav/CHANGELOG.md
  packages/main-nav/README.md
  packages/main-nav/package.json
  packages/main-nav/src/js/react.js
  packages/main-nav/tests/jquery/index.html
  packages/main-nav/tests/site/index.html
  scripts/helper.js
Labels: accessibility

#716 Removed keyword 'navigation' from aria-label in footer and main-nav
  CODE_OF_CONDUCT.md
  packages/footer/CHANGELOG.md
  packages/footer/README.md
  packages/footer/package.json
  packages/footer/src/js/react.js
  packages/footer/tests/site/index.html
  packages/main-nav/CHANGELOG.md
  packages/main-nav/README.md
  packages/main-nav/package.json
  packages/main-nav/src/js/react.js
  packages/main-nav/tests/jquery/index.html
  packages/main-nav/tests/site/index.html
  scripts/helper.js
Labels: accessibility

#717 Hot fix - update footer docs
  auds.json
  packages/footer/CHANGELOG.md
  packages/footer/README.md
Labels: documentation

#701 Add form component
  README.md
  auds.json
  package-lock.json
  packages/form/CHANGELOG.md
  packages/form/LICENSE
  packages/form/README.md
  packages/form/package-lock.json
  packages/form/package.json
  packages/form/src/js/react.js
  packages/form/src/sass/_dependencies.scss
  packages/form/src/sass/_globals.scss
  packages/form/src/sass/_module.scss
  packages/form/src/sass/_print.scss
  packages/form/tests/index.html
  packages/form/tests/react/.babelrc
  packages/form/tests/react/index.html
  packages/form/tests/react/index.js
  packages/form/tests/react/webpack.config.js
  packages/form/tests/site/index.html
  packages/form/tests/site/test.scss
Labels: enhancement, module: form

#719 Form component
  README.md
  auds.json
  package-lock.json
  packages/form/CHANGELOG.md
  packages/form/LICENSE
  packages/form/README.md
  packages/form/package-lock.json
  packages/form/package.json
  packages/form/src/js/react.js
  packages/form/src/sass/_dependencies.scss
  packages/form/src/sass/_globals.scss
  packages/form/src/sass/_module.scss
  packages/form/src/sass/_print.scss
  packages/form/tests/index.html
  packages/form/tests/react/.babelrc
  packages/form/tests/react/index.html
  packages/form/tests/react/index.js
  packages/form/tests/react/webpack.config.js
  packages/form/tests/site/index.html
  packages/form/tests/site/test.scss
Labels: new component

#730 Update AUlabel selector to add `margin-top` for all `HTMLInputElement`
  packages/form/CHANGELOG.md
  packages/form/README.md
  packages/form/package.json
  packages/form/src/sass/_module.scss
  packages/form/tests/react/index.js
  packages/link-list/CHANGELOG.md
  packages/link-list/README.md
  packages/link-list/package.json
  packages/link-list/src/js/react.js
Labels: bug, enhancement

#738 Use hint colours from core
  auds.json
  packages/form/CHANGELOG.md
  packages/form/README.md
  packages/form/package.json
  packages/form/src/sass/_globals.scss
  packages/form/src/sass/_module.scss
Labels: enhancement

#739 Use hint colours from core component
  auds.json
  packages/form/CHANGELOG.md
  packages/form/README.md
  packages/form/package.json
  packages/form/src/sass/_globals.scss
  packages/form/src/sass/_module.scss
Labels: enhancement
