Repository govau/design-system-components, pull requests merged in 2019-01, with the labels that each got.

#579 Radio button focus is rounded
  packages/control-input/CHANGELOG.md
  packages/control-input/README.md
  packages/control-input/package.json
  packages/control-input/src/sass/_module.scss
  uikit.json
Labels: enhancement

#582 Fix parent props rendering causing accordion to open and close
  packages/accordion/CHANGELOG.md
  packages/accordion/README.md
  packages/accordion/package.json
  packages/accordion/src/js/react.js
  packages/accordion/tests/react/index.js
  packages/side-nav/CHANGELOG.md
  packages/side-nav/README.md
  packages/side-nav/package.json
  uikit.json
Labels: bug

#581 Radio button circle focus, callout heading, page alerts remove role="alert"
  packages/accordion/CHANGELOG.md
  packages/accordion/README.md
  packages/accordion/package.json
  packages/accordion/src/js/react.js
  packages/accordion/tests/react/index.js
  packages/callout/CHANGELOG.md
  packages/callout/README.md
  packages/callout/package.json
  packages/callout/src/js/react.js
  packages/callout/src/sass/_module.scss
  packages/callout/tests/react/index.js
  packages/callout/tests/site/index.html
  packages/control-input/CHANGELOG.md
  packages/control-input/README.md
  packages/control-input/package.json
  packages/control-input/src/sass/_module.scss
  packages/page-alerts/CHANGELOG.md
  packages/page-alerts/README.md
  packages/page-alerts/package.json
  packages/page-alerts/src/js/react.js
  packages/page-alerts/tests/site/index.html
  packages/side-nav/CHANGELOG.md
  packages/side-nav/README.md
  packages/side-nav/package.json
  uikit.json
Labels: bug, enhancement

#590 Remove aria-selected accordion button
  auds.json
  packages/accordion/CHANGELOG.md
  packages/accordion/README.md
  packages/accordion/package.json
  packages/accordion/src/js/jquery.js
  packages/accordion/src/js/module.js
  packages/accordion/src/js/react.js
  packages/accordion/tests/site/index.html
  packages/side-nav/CHANGELOG.md
  packages/side-nav/README.md
  packages/side-nav/package.json
  packages/side-nav/tests/jquery/index.html
  packages/side-nav/tests/site/index.html
Labels: accessibility

#591 Add title attribute to iframe examples
  auds.json
  packages/responsive-media/CHANGELOG.md
  packages/responsive-media/README.md
  packages/responsive-media/package.json
  packages/responsive-media/tests/site/index.html
Labels: accessibility

#605 Fix issue with small radio button overlay
  auds.json
  package-lock.json
  packages/control-input/CHANGELOG.md
  packages/control-input/README.md
  packages/control-input/package.json
  packages/control-input/src/sass/_module.scss
Labels: bug

#606 Fix issue with small radio button overlay
  auds.json
  package-lock.json
  packages/control-input/CHANGELOG.md
  packages/control-input/README.md
  packages/control-input/package.json
  packages/control-input/src/sass/_module.scss
Labels: bug

#539 Color palette generation changes
  auds.json
  packages/core/CHANGELOG.md
  packages/core/README.md
  packages/core/package.json
  packages/core/src/sass/_globals.scss
  packages/core/tests/site/test.scss
Labels: accessibility, enhancement
