Repository govau/design-system-components, pull requests merged in 2019-08, with the labels that each got.

#862 Fix version constraint for Core in Form component.
  packages/form/package.json
Labels: dependencies

#863 Update @gov.au/core dependency for the form component
  auds.json
  packages/form/CHANGELOG.md
  packages/form/README.md
  packages/form/package.json
Labels: dependencies

#849 Main Navigation - Screen Reader Mobile view
  packages/main-nav/CHANGELOG.md
  packages/main-nav/README.md
  packages/main-nav/package.json
  packages/main-nav/src/js/module.js
  packages/main-nav/src/js/react.js
  packages/main-nav/tests/jquery/index.html
  packages/main-nav/tests/site/index.html
Labels: accessibility

#865 Main-nav add aria-expaneded to open/close button
  packages/main-nav/CHANGELOG.md
  packages/main-nav/README.md
  packages/main-nav/package.json
  packages/main-nav/src/js/module.js
  packages/main-nav/src/js/react.js
  packages/main-nav/tests/jquery/index.html
  packages/main-nav/tests/site/index.html
Labels: accessibility

#866 Update auds.json
  auds.json
Labels: dependencies

#861 Searchbox component
  README.md
  auds.json
  package-lock.json
  packages/page-alerts/src/sass/_module.scss
  packages/searchbox/CHANGELOG.md
  packages/searchbox/LICENSE
  packages/searchbox/README.md
  packages/searchbox/package.json
  packages/searchbox/src/js/react.js
  packages/searchbox/src/sass/_dependencies.scss
  packages/searchbox/src/sass/_globals.scss
  packages/searchbox/src/sass/_module.scss
  packages/searchbox/src/sass/_print.scss
  packages/searchbox/tests/index.html
  packages/searchbox/tests/react/.babelrc
  packages/searchbox/tests/react/index.html
  packages/searchbox/tests/react/index.js
  packages/searchbox/tests/react/webpack.config.js
  packages/searchbox/tests/site/index.html
  packages/searchbox/tests/site/search--dark.png
  packages/searchbox/tests/site/search.png
  packages/searchbox/tests/site/test.scss
Labels: new component

#871 Searchbox component dev --> master
  README.md
  auds.json
  package-lock.json
  packages/page-alerts/src/sass/_module.scss
  packages/searchbox/CHANGELOG.md
  packages/searchbox/LICENSE
  packages/searchbox/README.md
  packages/searchbox/package.json
  packages/searchbox/src/js/react.js
  packages/searchbox/src/sass/_dependencies.scss
  packages/searchbox/src/sass/_globals.scss
  packages/searchbox/src/sass/_module.scss
  packages/searchbox/src/sass/_print.scss
  packages/searchbox/tests/index.html
  packages/searchbox/tests/react/.babelrc
  packages/searchbox/tests/react/index.html
  packages/searchbox/tests/react/index.js
  packages/searchbox/tests/react/webpack.config.js
  packages/searchbox/tests/site/index.html
  packages/searchbox/tests/site/search--dark.png
  packages/searchbox/tests/site/search.png
  packages/searchbox/tests/site/test.scss
Labels: new component

#872 Fix incorrect js doc with searchbox
  auds.json
  packages/searchbox/CHANGELOG.md
  packages/searchbox/README.md
  packages/searchbox/package.json
  packages/searchbox/src/js/react.js
  packages/searchbox/src/sass/_globals.scss
  packages/searchbox/src/sass/_module.scss
Labels: documentation, enhancement

#874 Add styling for secondary buttons
  auds.json
  packages/searchbox/CHANGELOG.md
  packages/searchbox/README.md
  packages/searchbox/package.json
  packages/searchbox/src/sass/_globals.scss
  packages/searchbox/src/sass/_module.scss
  packages/searchbox/tests/site/index.html
  packages/searchbox/tests/site/test.scss
Labels: documentation

#875 Update package lock
  package-lock.json
Labels: dependencies

#877 Fix vulnerablities components
  package-lock.json
  packages/accordion/package-lock.json
  packages/animate/package-lock.json
  packages/body/package-lock.json
  packages/breadcrumbs/package-lock.json
  packages/core/package-lock.json
Labels: dependencies

#879 buttons package lock
  packages/buttons/package-lock.json
Labels: dependencies

#880 increase size for icon
  packages/searchbox/CHANGELOG.md
  packages/searchbox/README.md
  packages/searchbox/package.json
  packages/searchbox/src/sass/_globals.scss
Labels: enhancement
