Repository govau/design-system-components, pull requests merged in 2019-02, with the labels that each got.

#625 Ran `npm audit fix`
  package-lock.json
  package.json
Labels: enhancement

#645 Bumped accordion (#644)
  auds.json
  packages/accordion/CHANGELOG.md
  packages/accordion/README.md
  packages/accordion/package.json
Labels: bug

#650 Removed dev dep check for non-react components
  scripts/helper.js
Labels: bug

#660 Removed unused fragment import
  packages/accordion/tests/react/index.js
  packages/breadcrumbs/src/js/react.js
  packages/breadcrumbs/tests/react/index.js
  packages/buttons/src/js/react.js
  packages/buttons/tests/react/index.js
  packages/control-input/src/js/react.js
  packages/cta-link/src/js/react.js
  packages/cta-link/tests/react/index.js
  packages/direction-links/src/js/react.js
  packages/direction-links/tests/react/index.js
  packages/footer/src/js/react.js
  packages/header/src/js/react.js
  packages/header/tests/react/index.js
  packages/headings/src/js/react.js
  packages/inpage-nav/src/js/react.js
  packages/keyword-list/src/js/react.js
  packages/keyword-list/tests/react/index.js
  packages/link-list/src/js/react.js
  packages/link-list/tests/react/index.js
  packages/main-nav/tests/react/index.js
  packages/page-alerts/src/js/react.js
  packages/progress-indicator/tests/react/index.js
  packages/select/src/js/react.js
  packages/side-nav/tests/react/index.js
  packages/skip-link/src/js/react.js
  packages/tags/src/js/react.js
  packages/tags/tests/react/index.js
  packages/text-inputs/src/js/react.js
Labels: enhancement

#661 Use explicit labelling for control inputs
  auds.json
  packages/control-input/CHANGELOG.md
  packages/control-input/README.md
  packages/control-input/package.json
  packages/control-input/src/js/react.js
  packages/control-input/src/sass/_module.scss
  packages/control-input/tests/react/index.js
  packages/control-input/tests/site/index.html
Labels: accessibility
