Repository govau/design-system-components, pull requests merged in 2019-06, with the labels that each got.

#800 Use cloud.gov.au naming convention for env vars in circleci
  .circleci/config.yml
Labels: security

#801 Use cloud.gov.au naming convention for env vars in circleci
  .circleci/config.yml
Labels: security

#774 Card component [WIP]
  README.md
  auds.json
  packages/card/CHANGELOG.md
  packages/card/LICENSE
  packages/card/README.md
  packages/card/package.json
  packages/card/src/js/react.js
  packages/card/src/sass/_dependencies.scss
  packages/card/src/sass/_globals.scss
  packages/card/src/sass/_module.scss
  packages/card/src/sass/_print.scss
  packages/card/tests/index.html
  packages/card/tests/react/.babelrc
  packages/card/tests/react/index.html
  packages/card/tests/react/index.js
  packages/card/tests/react/webpack.config.js
  packages/card/tests/site/index.html
  packages/card/tests/site/test.scss
Labels: new component

#802 Card component
  README.md
  auds.json
  packages/card/CHANGELOG.md
  packages/card/LICENSE
  packages/card/README.md
  packages/card/package.json
  packages/card/src/js/react.js
  packages/card/src/sass/_dependencies.scss
  packages/card/src/sass/_globals.scss
  packages/card/src/sass/_module.scss
  packages/card/src/sass/_print.scss
  packages/card/tests/index.html
  packages/card/tests/react/.babelrc
  packages/card/tests/react/index.html
  packages/card/tests/react/index.js
  packages/card/tests/react/webpack.config.js
  packages/card/tests/site/index.html
  packages/card/tests/site/test.scss
Labels: new component

#803 Remove unnecessary css property
  auds.json
  packages/card/src/sass/_module.scss
Labels: bug

#804 Add background color to card
  packages/card/CHANGELOG.md
  packages/card/README.md
  packages/card/package.json
  packages/card/src/sass/_globals.scss
  packages/card/src/sass/_module.scss
Labels: enhancement

#805 Add background color to card
  packages/card/CHANGELOG.md
  packages/card/README.md
  packages/card/package.json
  packages/card/src/sass/_globals.scss
  packages/card/src/sass/_module.scss
Labels: enhancement

#806 Update auds.json
  auds.json
Labels: enhancement

#775 WIP - Hiding arrow icon in direction links from screen readers
  packages/direction-links/CHANGELOG.md
  packages/direction-links/README.md
  packages/direction-links/package.json
  packages/direction-links/src/js/react.js
  packages/direction-links/src/sass/_module.scss
  packages/direction-links/src/sass/_print.scss
  packages/direction-links/tests/site/index.html
Labels: enhancement

#807 Refactor direction links: hide arrows from screen reader
  packages/card/README.md
  packages/direction-links/CHANGELOG.md
  packages/direction-links/README.md
  packages/direction-links/package.json
  packages/direction-links/src/js/react.js
  packages/direction-links/src/sass/_module.scss
  packages/direction-links/src/sass/_print.scss
  packages/direction-links/tests/site/index.html
Labels: accessibility, enhancement

#809 Remove console log, update naming on card component
  auds.json
  packages/card/CHANGELOG.md
  packages/card/README.md
  packages/card/package.json
  packages/card/src/js/react.js
  packages/card/src/sass/_module.scss
  packages/card/tests/react/index.js
  packages/card/tests/site/index.html
Labels: enhancement

#810 Remove console log, update naming on card component, add jsdoc, security patch
  auds.json
  packages/animate/package-lock.json
  packages/card/CHANGELOG.md
  packages/card/README.md
  packages/card/package.json
  packages/card/src/js/react.js
  packages/card/src/sass/_module.scss
  packages/card/tests/react/index.js
  packages/card/tests/site/index.html
Labels: enhancement

#811 Fix spacing bug on class names card component
  packages/card/CHANGELOG.md
  packages/card/README.md
  packages/card/package.json
  packages/card/src/js/react.js
Labels: bug

#812 Update auds.json to reflect card v0.1.3
  auds.json
Labels: documentation

#813 Remove unneccessary styling and add comments in cards sass
  auds.json
  packages/card/CHANGELOG.md
  packages/card/README.md
  packages/card/package.json
  packages/card/src/sass/_module.scss
Labels: documentation, enhancement

#814 Make use of responsive-media for card images
  auds.json
  packages/card/CHANGELOG.md
  packages/card/README.md
  packages/card/package.json
  packages/card/src/sass/_module.scss
  packages/card/tests/react/index.js
  packages/card/tests/site/index.html
Labels: enhancement

#817 Refactor card sass, add dark/alt tests, remove body export
  auds.json
  packages/card/CHANGELOG.md
  packages/card/README.md
  packages/card/package.json
  packages/card/src/js/react.js
  packages/card/src/sass/_module.scss
  packages/card/tests/react/index.js
  packages/card/tests/site/index.html
Labels: enhancement

#818 Card add dark, alt prop, remove unnecessary export, add feature headers
  CONTRIBUTING.md
  auds.json
  packages/card/CHANGELOG.md
  packages/card/README.md
  packages/card/package.json
  packages/card/src/js/react.js
  packages/card/src/sass/_module.scss
  packages/card/tests/react/index.js
  packages/card/tests/site/index.html
Labels: enhancement

#819 Add react props for alt/dark feature headers and footers cards
  packages/card/CHANGELOG.md
  packages/card/README.md
  packages/card/package.json
  packages/card/src/js/react.js
  packages/card/src/sass/_module.scss
  packages/card/tests/react/index.js
  packages/card/tests/site/index.html
Labels: enhancement

#820 Use unit instead of rem
  packages/card/CHANGELOG.md
  packages/card/README.md
  packages/card/package.json
  packages/card/src/sass/_module.scss
Labels: bug

#821 Update auds.json
  auds.json
Labels: documentation
