Repository govau/design-system-components, pull requests merged in 2019-05, with the labels that each got.

#750 Change body print `background-color` from #fff to transparent
  packages/body/CHANGELOG.md
  packages/body/README.md
  packages/body/package.json
  packages/body/src/sass/_print.scss
Labels: discussion, enhancement

#752 Added `no-cache` header to deployments
  .deploy/nginx/nginx-production.conf
  .deploy/nginx/nginx-staging.conf
  .deploy/nginx/nginx-testing.conf
Labels: enhancement

#753 Bumped deps, mitigate node-sass security conflict + no-cache
  .deploy/nginx/nginx-production.conf
  .deploy/nginx/nginx-staging.conf
  .deploy/nginx/nginx-testing.conf
  lerna.json
  package-lock.json
  package.json
  packages/accordion/package-lock.json
  packages/animate/package.json
  packages/body/package-lock.json
  packages/breadcrumbs/package-lock.json
  packages/buttons/package-lock.json
  packages/callout/package-lock.json
  packages/control-input/package-lock.json
  packages/core/package-lock.json
  packages/cta-link/package-lock.json
  packages/direction-links/package-lock.json
  packages/footer/package-lock.json
  packages/grid-12/package-lock.json
  packages/header/package-lock.json
  packages/headings/package-lock.json
  packages/inpage-nav/package-lock.json
  packages/keyword-list/package-lock.json
  packages/link-list/package-lock.json
  packages/main-nav/package-lock.json
  packages/page-alerts/package-lock.json
  packages/progress-indicator/package-lock.json
  packages/responsive-media/package-lock.json
  packages/select/package-lock.json
  packages/skip-link/package-lock.json
  packages/tags/package-lock.json
  packages/text-inputs/package-lock.json
Labels: maintenance, security

#755 fix onClick property's type to function instead of object
  packages/link-list/src/js/react.js
Labels: bug

#740 Table component
  README.md
  auds.json
  packages/table/CHANGELOG.md
  packages/table/LICENSE
  packages/table/README.md
  packages/table/package-lock.json
  packages/table/package.json
  packages/table/src/js/react.js
  packages/table/src/sass/_dependencies.scss
  packages/table/src/sass/_globals.scss
  packages/table/src/sass/_module.scss
  packages/table/src/sass/_print.scss
  packages/table/tests/index.html
  packages/table/tests/react/.babelrc
  packages/table/tests/react/index.html
  packages/table/tests/react/index.js
  packages/table/tests/react/webpack.config.js
  packages/table/tests/site/index.html
  packages/table/tests/site/test.scss
Labels: new component

#757 Remove comment causing white space error
  packages/table/src/js/react.js
Labels: bug

#763 Update numeric cell font, fix typos in readme and JSdoc
  auds.json
  packages/table/CHANGELOG.md
  packages/table/README.md
  packages/table/package.json
  packages/table/src/js/react.js
  packages/table/src/sass/_globals.scss
  packages/table/src/sass/_module.scss
  packages/table/tests/site/index.html
Labels: documentation, enhancement

#764 Update font numeric cell, update contact email, fix typos in read me and jsdoc for table
  README.md
  auds.json
  packages/table/CHANGELOG.md
  packages/table/README.md
  packages/table/package.json
  packages/table/src/js/react.js
  packages/table/src/sass/_globals.scss
  packages/table/src/sass/_module.scss
  packages/table/tests/site/index.html
Labels: documentation, enhancement

#768 Add margin top to text area preceded by label, hint text or error
  packages/form/CHANGELOG.md
  packages/form/README.md
  packages/form/package.json
  packages/form/src/sass/_module.scss
  packages/form/tests/site/index.html
Labels: bug, enhancement

#769 Add margin top to text area preceded by label, hint text or error
  packages/form/CHANGELOG.md
  packages/form/README.md
  packages/form/package.json
  packages/form/src/sass/_module.scss
  packages/form/tests/site/index.html
Labels: bug, enhancement

#770 Update AUDS json, update packages
  auds.json
  package-lock.json
  package.json
Labels: enhancement

#771 Update AUDS json, update packages
  auds.json
  package-lock.json
  package.json
Labels: enhancement

#777 Use font-variant property instead of "verdana" font
  auds.json
  packages/table/CHANGELOG.md
  packages/table/README.md
  packages/table/package.json
  packages/table/src/sass/_globals.scss
  packages/table/src/sass/_module.scss
Labels: enhancement

#778 Use font-variant property instead of "verdana" font for numerical table cells
  auds.json
  packages/table/CHANGELOG.md
  packages/table/README.md
  packages/table/package.json
  packages/table/src/sass/_globals.scss
  packages/table/src/sass/_module.scss
Labels: enhancement

#780 Remove js plugin from table package json
  packages/table/CHANGELOG.md
  packages/table/README.md
  packages/table/package.json
Labels: bug

#781 Remove pancake js dependency from table, update auds.json
  auds.json
  packages/table/package.json
Labels: bug

#783 accordion security fix
  packages/accordion/package-lock.json
Labels: security

#788 Security, update tar to 4.4.8
  packages/body/package-lock.json
  packages/breadcrumbs/package-lock.json
  packages/buttons/package-lock.json
  packages/core/package-lock.json
Labels: security

#793 Security patches fs stream
  packages/accordion/package-lock.json
  packages/body/package-lock.json
  packages/breadcrumbs/package-lock.json
  packages/core/package-lock.json
Labels: security

#795 fs stream bump on buttons
  packages/buttons/package-lock.json
Labels: security
